require('./app.module.js');
require('./core/core.module.js');
require('./lgtm/lgtm.module.js');
require('./toolbar/toolbar.module.js')
require('./toolbar/toolbar.controller.js');;
require('./lgtm/login.controller.js');
require('./lgtm/lgtm.list.controller.js');
require('./lgtm/lgtm.routes.js');
require('./services/program.service.js');
require('./services/login.service.js');
require('./services/http-interceptor.service.js');
require('./services/token.service.js');
